name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # ----------- BACKEND --------------
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    env:
      DATABASE_URL: postgresql://postgres:test@localhost:5432/lovelace_test
      JWT_SECRET: ${{ secrets.JWT_SECRET_TEST }}
    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_PASSWORD: test
          POSTGRES_DB: lovelace_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s

    steps:
      - uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "npm"
          cache-dependency-path: backend/package-lock.json
      - name: Installer les dépendances
        run: npm ci
      - name: Tests bdd
        run: npm run db:migrate:up && npm run db:seed:up

      # - name: Linter
      #   run: npm run lint

      - name: Tests
        run: npm test

  # # ----------- FRONTEND --------------
  # frontend:
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: ./frontend
  #   steps:
  #     - uses: actions/checkout@v6

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v6
  #       with:
  #         node-version: "24"
  #         cache: "npm"
  #         cache-dependency-path: frontend/package-lock.json

  #     - name: Installer les dépendances
  #       run: npm ci

  #     # - name: Linter
  #     #   run: npm run lint

  #     - name: Tests
  #       run: npm test
